/**
 * Auto-generation of `vite-env.d.ts` typings.
 *
 * The plugin emits a project-root `vite-env.d.ts` that references
 * `vite/client` (so `import.meta.env` itself is typed) and that declares
 * the union of:
 *
 *   - vars the code actually consumes (collected by the transform pass),
 *   - vars declared in the .env chain (already resolved by Vite at build
 *     time and exposed on `config.env`).
 *
 * If the user already has a `vite-env.d.ts` in the project root, we leave
 * it alone — the user is in charge of their own typings.
 */

export interface ViteEnvInput {
  /** Names that the transform pass actually rewrote. */
  used: ReadonlySet<string>;
  /** Everything Vite resolved from the .env chain. */
  env: Record<string, unknown>;
  /**
   * Optional extra sources the user wired up via `defaults` or
   * `extraFiles`. The plugin treats them as a flat string map.
   */
  extras?: Readonly<Record<string, unknown>>;
  /** Name of the global the plugin writes to (`__APP_ENV__` by default). */
  globalName: string;
  /** Vite's `envPrefix` — used to filter env keys to the user-defined set. */
  envPrefix: string | readonly string[];
  /** Predict: which env vars would be rewritten. */
  shouldReplace: (name: string) => boolean;
}

/** Vite-internal env keys that must never appear in user typings. */
const VITE_INTERNALS: ReadonlySet<string> = new Set([
  "MODE",
  "BASE_URL",
  "PROD",
  "DEV",
  "SSR",
  "LEGACY",
]);

/**
 * Compute the deduped, sorted list of typed env keys.
 *
 * The set is the union of:
 *   1. vars actually consumed by source code, and
 *   2. vars present in the .env chain AND matching the user prefix.
 *
 * The `env`-chain side only matters in build mode. In dev we still want to
 * expose the keys the app reads, so the caller passes `used` and we
 * include those unconditionally.
 */
export function collectEnvKeys(input: ViteEnvInput): string[] {
  const out = new Set<string>();

  for (const name of input.used) {
    if (VITE_INTERNALS.has(name)) continue;
    out.add(name);
  }

  const prefixList = Array.isArray(input.envPrefix)
    ? input.envPrefix
    : [input.envPrefix as string];

  for (const [key, value] of Object.entries(input.env)) {
    if (VITE_INTERNALS.has(key)) continue;
    if (typeof value !== "string") continue;
    // Only consider vars that match at least one configured prefix; this
    // respects a custom `envPrefix` array.
    if (!prefixList.some((p) => key.length > p.length && key.startsWith(p))) {
      continue;
    }
    out.add(key);
  }

  // Also include vars coming from inline `defaults` or `extraFiles`.
  // We accept any prefix here — the user explicitly opted in by
  // authoring that file, so we treat it as the source of truth.
  if (input.extras) {
    for (const key of Object.keys(input.extras)) {
      if (VITE_INTERNALS.has(key)) continue;
      out.add(key);
    }
  }

  return [...out].sort();
}

/**
 * Render the `vite-env.d.ts` source. The generated file:
 *
 *   1. references `vite/client` so `import.meta.env` itself is typed,
 *   2. augments `ImportMetaEnv` with the union of known VITE_* keys,
 *   3. augments `ImportMetaEnv` with the runtime global the plugin writes
 *      to, so users can read either path with full typings.
 */
export function renderViteEnvDts(keys: readonly string[], globalName: string): string {
  const indent = "    "; // 4 spaces under ImportMetaEnv
  const seen = new Set<string>();
  const lines: string[] = [
    `/// <reference types="vite/client" />`,
    ``,
    `/**`,
    ` * Auto-generated by vite-plugin-appsettings.`,
    ` * Safe to delete — the plugin will recreate it on the next build.`,
    ` * Add custom typings in a separate \`.d.ts\` file to avoid losing them.`,
    ` */`,
    ``,
    `interface ImportMetaEnv {`,
  ];

  for (const key of keys) {
    if (seen.has(key)) continue;
    seen.add(key);
    lines.push(`${indent}readonly ${key}: string;`);
  }
  // `globalThis[globalName]` mirror — same shape as the JSON we serve.
  lines.push(
    `${indent}readonly [key: \`\${string}\`]: unknown;`,
  );

  lines.push(`}`, ``, `interface ImportMeta {`, `${indent}readonly env: ImportMetaEnv;`, `}`, ``);

  // Also expose the runtime global on `globalThis` so
  // `import("vite-plugin-appsettings/runtime").loadRuntime()` or
  // ad-hoc reads from `globalThis[globalName]` are typed.
  lines.push(
    `interface Window {`,
    `${indent}${globalName}: ImportMetaEnv;`,
    `}`,
    ``,
    `// eslint-disable-next-line no-var`,
    `declare var ${globalName}: ImportMetaEnv;`,
    ``,
  );

  return lines.join("\n");
}
